MIN_ACTIVE_KW_FOR_CHARGE = 20
THRESHOLD_METER_AC_VOLTAGE = 380 / 2

AUTHORITY_USER_LEVEL_MIN = 1
AUTHORITY_USER_LEVEL_MAX = 3

AUTHORITY_CUSTOMER = 1
AUTHORITY_SERVICEMAN = 2
AUTHORITY_MANAGER = 3

AUTHORITY_ADMIN_LEVEL_MIN = 4
AUTHORITY_ADMIN_LEVEL_MAX = 99

AUTHORITY_SYNERGY = 4
AUTHORITY_ENERGY = 5
AUTHORITY_INNOVATION = 6
AUTHORITY_LOCAL_ADMIN = 7
AUTHORITY_ADMIN = 99

PS_STATUS_NOT_INSTALLED = 0 ## 설치전
PS_STATUS_INSTALLING = 1 ## 설치중
PS_STATUS_INSTALLED = 2 ## 설치완료
PS_STATUS_SERVICE_ON = 3 ## 이용중
PS_STATUS_SERVICE_STOP = 4 ## 이용중지
PS_STATUS_REQUEST_DEMOLITION = 5 ## 철거요청
PS_STATUS_DEMOLISHED = 6 ## 철거중
PS_STATUS_DEMOLITION_COMPLETED = 7 ## 철거완료
PS_STATUS_SERVICE_TERMINATION = 8 ## 서비스 해지
PS_STATUS_TEST = 9 ## 테스트
PS_STATUS_NOT_USED = 10 ## 사용안함

COLLECT_MODULES = ['inverter', 'pcs', 'bms', 'pms', 'meter', 'emsEnv', 'weather', 'combinerBox', 'isoMeter']

DIFF_UTC_TO_KST = 9